## Defining States

The most basic states of a claim are "open" and "closed". For purposes of our case study we further refined our model to indicate whether the claim had a non-zero value:
  
* Open Zero (oz): open with no value
* Open Non-Zero (onz): open with value
* Closed Zero (cz): closed with no value
* Closed Non-Zero (cnz): closed with value
  
This refinement allows us to answer the question as to "how the claim closed" by observing if the claim closes with or without value. 

As a reminder, the synthetic data we are using only includes payments and not incurred values. In practice, the "with value" could relate to incurred value on open claims rather than payments.

Our case study is a more simplistic approach to defining transition states. There are countless ways to define these states, for example, we could introduce a threshold such as \$500 thousand of value. We would then have three open states; open zero, open with value less than \$500 thousand, and open with value greater than or equal to $500 thousand. Other examples include incorporating paid to incurred ratios or "type" of claim (e.g., observation, claim or suit). As we further refine the states used in the model, the model complexity will increase. In general defining of states should consider how available variables might predict the _settlement lag_ or _severity_ of claims.
